kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-net-raw
allowPrivilegedContainer: true
allowedCapabilities:
  - "NET_RAW"
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
groups:
priority: 10
